stages:
  - validate

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_TLS_CERTDIR: "/certs"

workspace-validate:
  stage: validate
  image: docker:27-cli
  services:
    - docker:27-dind
  before_script:
    - apk add --no-cache bash make git py3-yamllint
  script:
    - make validate
