stages:
  - validate

variables:
  GIT_SUBMODULE_STRATEGY: none
  DOCKER_TLS_CERTDIR: "/certs"

workspace-validate:
  stage: validate
  image: docker:27-cli
  services:
    - docker:27-dind
  before_script:
    - apk add --no-cache bash make git py3-yamllint
    - rm -rf tourism-platform
    - git clone --depth 1 "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/xotabeach/tourism-platform.git" tourism-platform
  script:
    - make -C tourism-platform validate
